# Generated by Django 5.0.7 on 2024-07-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_capture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='device_info',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
