# Generated by Django 5.0.7 on 2024-07-11 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_capture', '0002_userdetail_device_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
